### ISSUE TITLE
Ability to configure the button text.

### ISSUE THREAD

**Issue by nextpulse** [AptoPayments/apto-pci-sdk-web#75]
**Problem**
The button for OTP is hardcoded to 'Send'
**Proposed solution**
Offer an init option to replace this text.

**Comment by IagoLast** [comment]
Hi @nextpulse thx for the suggestion.

We will add an init option to configure this text in the next weeks :)

**Comment by alejandraarri** [comment]
Hi @nextpulse,

just wanted to let you know that we are working on adding that feature. We'll keep you posted!! 😊

**Comment by alejandraarri** [comment]
Hi @nextpulse,

we have released a new version of the PCI SDK Web that includes an option to customize the text for the buttons on the forms. As you can see in the [docs](https://docs.aptopayments.com/docs/sdks/Web/pci_sdk_web#optionsobject-properties) a `otpSubmitButton` or a `setPinSubmitButton` can be set in the `values` to update these texts. Check the [4.0.0 version](https://www.npmjs.com/package/@apto-payments/pci-sdk-web) and the [migration guide](https://docs.aptopayments.com/docs/guides/Migrations/PCI%20SDK%20Web/migration) in case you want to update.

**Comment by IagoLast** [comment]
I'm closing this because it was included on on v4 🚀
